
services:
  overlay:
    image: taskwhiz:overlay
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:?}
      target: overlay
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
  
  dev:
    extends: overlay
    image: taskwhiz:dev
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./taskwhiz:/colcon_ws/src/taskwhiz:rw
    user: user
    command: sleep infinity